### ISSUE TITLE
Gene families mapping

### ISSUE THREAD

**Issue by fbeghini** [seandavi/curatedMetagenomicsNextflow#6]
@paolinomanghi and I were thinking about not including directly the mapped gene families as a resource for cMD. HUMAnN provides mapping for 
- EC
- KO
- GO
- eggNOG
- PFAM
plus, provides all the descriptions for UniRef90/50 and the mapped categories.

Instead of providing these files, that should be computed for both the stratified and unstratified gene families, we thought about having a function that downloads the mapping files and another that, given the gene families (stratified or unstratified), it generates a table with the mapped gene families and/or the description.

What do you all guys think? @seandavi @lwaldron @nsegata @vjcitn

**Comment by nsegata** [comment]
Interesting! I think that if we go with this option to compute "real time"
the mapping, the question is: how much do you think it would take for a
user to download the entire cMD and convert everything to, let's say, PFAM?
If it is few minutes then that's great, otherwise I'm not sure...

thanks
Nicola

**Comment by paolinomanghi** [comment]
Me and Francesco discussed this this morning. The idea is that it should be
unitary cost (fast), otherwise I agree with you: providing all the outputs
would be
nice but considering the stratified and unstratified output, gene-families,
pathways, pathcoverage and say 3 of the grouping strategy is already 12
files and is not complete.

Paolo

**Comment by seandavi** [comment]
Will close for now. We can revisit if needed.
